// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtzUenynNPvrWU-_SaRXdZbUuTyFYK2w',
    appId: '1:588556284203:web:b98251d034f1a7db3f956e',
    messagingSenderId: '588556284203',
    projectId: 'helperhive-vishnu',
    authDomain: 'helperhive-vishnu.firebaseapp.com',
    storageBucket: 'helperhive-vishnu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDQeNy52_ceRjEl4qz6VrVovCBoASd9k',
    appId: '1:588556284203:android:6be528e02a1eeb533f956e',
    messagingSenderId: '588556284203',
    projectId: 'helperhive-vishnu',
    storageBucket: 'helperhive-vishnu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiq-ZCs-AUgs-Uy4bVWDoUxq7pmt6NJdY',
    appId: '1:588556284203:ios:c7f9bc4ab82aa21f3f956e',
    messagingSenderId: '588556284203',
    projectId: 'helperhive-vishnu',
    storageBucket: 'helperhive-vishnu.appspot.com',
    iosBundleId: 'com.example.helperhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiq-ZCs-AUgs-Uy4bVWDoUxq7pmt6NJdY',
    appId: '1:588556284203:ios:c7f9bc4ab82aa21f3f956e',
    messagingSenderId: '588556284203',
    projectId: 'helperhive-vishnu',
    storageBucket: 'helperhive-vishnu.appspot.com',
    iosBundleId: 'com.example.helperhive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtzUenynNPvrWU-_SaRXdZbUuTyFYK2w',
    appId: '1:588556284203:web:9f36c44248793c623f956e',
    messagingSenderId: '588556284203',
    projectId: 'helperhive-vishnu',
    authDomain: 'helperhive-vishnu.firebaseapp.com',
    storageBucket: 'helperhive-vishnu.appspot.com',
  );
}
